--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    "Роль" character varying(10) NOT NULL,
    "Имя" character varying(100) NOT NULL,
    "Фамилия" character varying(100) NOT NULL,
    "Отчество" character varying(100) NOT NULL,
    "Организация" character varying(255) NOT NULL,
    "Подразделение" character varying(255) NOT NULL,
    "Телефон" character varying(20) NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres_fxkms;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres_fxkms;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres_fxkms;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_components; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_components (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Серийный_Номер_Связанного_Объекта" character varying(255),
    "Инв_Номер_Бухгалтерии_Связанного_" character varying(255),
    "Заправлен" boolean NOT NULL,
    "Дата_последней_заправки" timestamp with time zone
);


ALTER TABLE public.assets_components OWNER TO postgres_fxkms;

--
-- Name: assets_components_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_consumables; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_consumables (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Количество" integer,
    "Сумма" double precision,
    "Серийный_Номер_Связанного_Объекта" character varying(255),
    "Инв_Номер_Бухгалтерии_Связанного_" character varying(255)
);


ALTER TABLE public.assets_consumables OWNER TO postgres_fxkms;

--
-- Name: assets_consumables_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_consumables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_consumables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_customasset; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_customasset (
    id bigint NOT NULL,
    "Название" character varying(255) NOT NULL
);


ALTER TABLE public.assets_customasset OWNER TO postgres_fxkms;

--
-- Name: assets_customasset_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_customasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_customasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_customassetdetails; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_customassetdetails (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Актив_id" bigint NOT NULL
);


ALTER TABLE public.assets_customassetdetails OWNER TO postgres_fxkms;

--
-- Name: assets_customassetdetails_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_customassetdetails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_customassetdetails_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_equipments; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_equipments (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Серисная_Организация" character varying(255),
    "Диагональ" double precision,
    "Количество_Мегапикселей" double precision,
    "Количество_портов" integer,
    "Отпечатано_страниц" integer
);


ALTER TABLE public.assets_equipments OWNER TO postgres_fxkms;

--
-- Name: assets_equipments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_equipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_equipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_exportfile; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_exportfile (
    id bigint NOT NULL,
    file character varying(100) NOT NULL
);


ALTER TABLE public.assets_exportfile OWNER TO postgres_fxkms;

--
-- Name: assets_exportfile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_exportfile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_exportfile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_handbookcomponents; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_handbookcomponents (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Название" character varying(255),
    "Серийный_Номер_Связанного_Объекта" character varying(255),
    "Инв_Номер_Бухгалтерии_Связанного_" character varying(255)
);


ALTER TABLE public.assets_handbookcomponents OWNER TO postgres_fxkms;

--
-- Name: assets_handbookcomponents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_handbookcomponents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_handbookcomponents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_handbookconsumables; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_handbookconsumables (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Название" character varying(255),
    "Количество" integer,
    "Сумма" double precision,
    "Серийный_Номер_Связанного_Объекта" character varying(255),
    "Инв_Номер_Бухгалтерии_Связанного_" character varying(255),
    "Сотрудник" character varying(255)
);


ALTER TABLE public.assets_handbookconsumables OWNER TO postgres_fxkms;

--
-- Name: assets_handbookconsumables_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_handbookconsumables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_handbookconsumables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_handbookequipments; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_handbookequipments (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Название" character varying(255),
    "Серисная_Организация" character varying(255),
    "Диагональ" double precision,
    "Количество_Мегапикселей" double precision,
    "Количество_портов" integer,
    "Сотрудник" character varying(255)
);


ALTER TABLE public.assets_handbookequipments OWNER TO postgres_fxkms;

--
-- Name: assets_handbookequipments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_handbookequipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_handbookequipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_handbookprograms; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_handbookprograms (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Название" character varying(255),
    "Версия" character varying(255),
    "Ключ_Продукта" character varying(255),
    "Код_Активации" character varying(255),
    "Дистрибутив" character varying(255),
    "Сотрудник" character varying(255)
);


ALTER TABLE public.assets_handbookprograms OWNER TO postgres_fxkms;

--
-- Name: assets_handbookprograms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_handbookprograms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_handbookprograms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_movements; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_movements (
    id bigint NOT NULL,
    "Номер" character varying(255),
    "Название" character varying(255),
    "Статус" character varying(255),
    "Филиал_Отправитель" character varying(255),
    "Подразделение_Отправитель_Описан" character varying(255),
    "Подразделение_Отправитель_Телефо" character varying(255),
    "Подразделение_Отправитель_Адрес" character varying(255),
    "Подразделение_Получатель" character varying(255),
    "Подразделение_Получатель_Описани" character varying(255),
    "Подразделение_Получатель_Телефон" character varying(255),
    "Подразделение_Получатель_Адрес" character varying(255),
    "Сотрудник_Отправитель" character varying(255),
    "Сотрудник_Отправитель_Отдел" character varying(255),
    "Сотрудник_Отправитель_Должность" character varying(255),
    "Сотрудник_Отправитель_Описание" character varying(255),
    "Сотрудник_Получатель" character varying(255),
    "Сотрудник_Получатель_Отдел" character varying(255),
    "Сотрудник_Получатель_Должность" character varying(255),
    "Сотрудник_Получатель_Описание" character varying(255),
    "Компания" character varying(255),
    "Количество" integer,
    "Описание" character varying(255),
    "Создал" character varying(255),
    "Дата_Отправки" timestamp with time zone,
    "Пользователь_Отправитель" character varying(255),
    "Дата_Получения" timestamp with time zone,
    "Пользователь_Получатель" character varying(255),
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дополнительные_Поля" jsonb
);


ALTER TABLE public.assets_movements OWNER TO postgres_fxkms;

--
-- Name: assets_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_programs; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_programs (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Стоимость_с_содержимым" double precision,
    "Дата_Инвертаризации" timestamp with time zone,
    "Содержимое" character varying(255),
    "Инвентарный_Номер_Связанного_Объе" character varying(255),
    "Тип_Связанного_Объекта" character varying(255),
    "Модель_Связанного_Объекта" character varying(255),
    "Номер_Заказа" character varying(255),
    "Не_Инвент" boolean NOT NULL,
    "Дата_Изменения" timestamp with time zone,
    "Изменил" character varying(255),
    "Дата_последней_проверки" timestamp with time zone,
    "Адрес" character varying(255),
    "Широта" double precision,
    "Долгота" double precision,
    "Город" character varying(255),
    "Индекс" integer,
    "Сетевое_Имя" character varying(255),
    "IP_Адрес" character varying(255),
    "Домен" character varying(255),
    "MAC_Адрес" character varying(255),
    "Название" character varying(255),
    "Версия" character varying(255),
    "Ключ_Продукта" character varying(255),
    "Код_Активации" character varying(255),
    "Номер_Мульти_Лицензии" character varying(255),
    "Количество_Мульти_Лицензий" integer,
    "Лиценизя_До" date,
    "Дистрибутив" character varying(255),
    "Количество_пользователей" character varying(255)
);


ALTER TABLE public.assets_programs OWNER TO postgres_fxkms;

--
-- Name: assets_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_repairs; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.assets_repairs (
    id bigint NOT NULL,
    "Компания" character varying(255),
    "Местоположение" character varying(255),
    "Статус" character varying(255),
    "Производитель" character varying(255),
    "Серийный_Номер" character varying(255),
    "Инв_Номер_Бухгалтерии" character varying(255),
    "Стоимость" double precision,
    "Сотрудник" character varying(255) NOT NULL,
    "Сотрудник_Компания" character varying(255),
    "Сотрудник_Подразделение" character varying(255),
    "Сотрудник_Отдел" character varying(255),
    "Сотрудник_Офис" character varying(255),
    "Сотрудник_Должность" character varying(255),
    "Сотрудник_Телефон" character varying(255),
    "Сотрудник_Мобильный_Телефон" character varying(255),
    "Сотрудник_EMail" character varying(255),
    "Сотрудник_Логин" character varying(255),
    "Сотрудник_Пасспорт" character varying(255),
    "Описание" character varying(255),
    "Поставщик" character varying(255),
    "Примечания" character varying(255),
    "Дополнительные_Поля" jsonb,
    "Тип" character varying(255),
    "Модель" character varying(255),
    "Номер_Партии" character varying(255),
    "Гарантия_До" date,
    "Номер" character varying(255),
    "Дата_Поломки" timestamp with time zone,
    "Дата_Отправки" timestamp with time zone,
    "Дата_Возврата" timestamp with time zone,
    "Описание_Неисправности" character varying(255),
    "Ремонт_Примечания" character varying(255),
    "Ремонт_Сервисная_Организация" character varying(255),
    "Ремонт_Стоимость" double precision,
    "Создал" character varying(255),
    "Отправил" character varying(255),
    "Принял" character varying(255),
    "Ремонт_Дата_Изменения" timestamp with time zone,
    "Ремонт_Изменил" character varying(255),
    "Вид_Учётных_Единиц" character varying(255),
    "ID_Объекта" character varying(255),
    "Подразделение" character varying(255),
    "Сервисная_Организация" character varying(255)
);


ALTER TABLE public.assets_repairs OWNER TO postgres_fxkms;

--
-- Name: assets_repairs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.assets_repairs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_repairs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres_fxkms;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres_fxkms;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres_fxkms;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres_fxkms;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres_fxkms;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres_fxkms;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres_fxkms;

--
-- Name: transfers_transferrequest; Type: TABLE; Schema: public; Owner: postgres_fxkms
--

CREATE TABLE public.transfers_transferrequest (
    id bigint NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    object_id integer NOT NULL,
    content_type_id integer NOT NULL,
    from_user_id bigint NOT NULL,
    to_user_id bigint NOT NULL,
    CONSTRAINT transfers_transferrequest_object_id_check CHECK ((object_id >= 0))
);


ALTER TABLE public.transfers_transferrequest OWNER TO postgres_fxkms;

--
-- Name: transfers_transferrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE public.transfers_transferrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfers_transferrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: assets_components assets_components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_components
    ADD CONSTRAINT assets_components_pkey PRIMARY KEY (id);


--
-- Name: assets_consumables assets_consumables_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_consumables
    ADD CONSTRAINT assets_consumables_pkey PRIMARY KEY (id);


--
-- Name: assets_customasset assets_customasset_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_customasset
    ADD CONSTRAINT assets_customasset_pkey PRIMARY KEY (id);


--
-- Name: assets_customasset assets_customasset_Название_key; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_customasset
    ADD CONSTRAINT "assets_customasset_Название_key" UNIQUE ("Название");


--
-- Name: assets_customassetdetails assets_customassetdetails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_customassetdetails
    ADD CONSTRAINT assets_customassetdetails_pkey PRIMARY KEY (id);


--
-- Name: assets_equipments assets_equipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_equipments
    ADD CONSTRAINT assets_equipments_pkey PRIMARY KEY (id);


--
-- Name: assets_exportfile assets_exportfile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_exportfile
    ADD CONSTRAINT assets_exportfile_pkey PRIMARY KEY (id);


--
-- Name: assets_handbookcomponents assets_handbookcomponents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_handbookcomponents
    ADD CONSTRAINT assets_handbookcomponents_pkey PRIMARY KEY (id);


--
-- Name: assets_handbookconsumables assets_handbookconsumables_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_handbookconsumables
    ADD CONSTRAINT assets_handbookconsumables_pkey PRIMARY KEY (id);


--
-- Name: assets_handbookequipments assets_handbookequipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_handbookequipments
    ADD CONSTRAINT assets_handbookequipments_pkey PRIMARY KEY (id);


--
-- Name: assets_handbookprograms assets_handbookprograms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_handbookprograms
    ADD CONSTRAINT assets_handbookprograms_pkey PRIMARY KEY (id);


--
-- Name: assets_movements assets_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_movements
    ADD CONSTRAINT assets_movements_pkey PRIMARY KEY (id);


--
-- Name: assets_programs assets_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_programs
    ADD CONSTRAINT assets_programs_pkey PRIMARY KEY (id);


--
-- Name: assets_repairs assets_repairs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_repairs
    ADD CONSTRAINT assets_repairs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: transfers_transferrequest transfers_transferreques_from_user_id_to_user_id__aafd0312_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.transfers_transferrequest
    ADD CONSTRAINT transfers_transferreques_from_user_id_to_user_id__aafd0312_uniq UNIQUE (from_user_id, to_user_id, content_type_id, object_id);


--
-- Name: transfers_transferrequest transfers_transferrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.transfers_transferrequest
    ADD CONSTRAINT transfers_transferrequest_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: assets_customasset_Название_752e5598_like; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX "assets_customasset_Название_752e5598_like" ON public.assets_customasset USING btree ("Название" varchar_pattern_ops);


--
-- Name: assets_customassetdetails_Актив_id_4ae8b305; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX "assets_customassetdetails_Актив_id_4ae8b305" ON public.assets_customassetdetails USING btree ("Актив_id");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: transfers_transferrequest_content_type_id_3440cb11; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX transfers_transferrequest_content_type_id_3440cb11 ON public.transfers_transferrequest USING btree (content_type_id);


--
-- Name: transfers_transferrequest_from_user_id_c9511bcb; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX transfers_transferrequest_from_user_id_c9511bcb ON public.transfers_transferrequest USING btree (from_user_id);


--
-- Name: transfers_transferrequest_to_user_id_ffaedd79; Type: INDEX; Schema: public; Owner: postgres_fxkms
--

CREATE INDEX transfers_transferrequest_to_user_id_ffaedd79 ON public.transfers_transferrequest USING btree (to_user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assets_customassetdetails assets_customassetde_Актив_id_4ae8b305_fk_assets_cu; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.assets_customassetdetails
    ADD CONSTRAINT "assets_customassetde_Актив_id_4ae8b305_fk_assets_cu" FOREIGN KEY ("Актив_id") REFERENCES public.assets_customasset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transfers_transferrequest transfers_transferre_content_type_id_3440cb11_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.transfers_transferrequest
    ADD CONSTRAINT transfers_transferre_content_type_id_3440cb11_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transfers_transferrequest transfers_transferre_from_user_id_c9511bcb_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.transfers_transferrequest
    ADD CONSTRAINT transfers_transferre_from_user_id_c9511bcb_fk_accounts_ FOREIGN KEY (from_user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transfers_transferrequest transfers_transferre_to_user_id_ffaedd79_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres_fxkms
--

ALTER TABLE ONLY public.transfers_transferrequest
    ADD CONSTRAINT transfers_transferre_to_user_id_ffaedd79_fk_accounts_ FOREIGN KEY (to_user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

