# Generated by Django 5.1.4 on 2025-03-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_handbookcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookequipments',
            name='Модель',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handbookequipments',
            name='Производитель',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handbookequipments',
            name='Тип',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
