# Generated by Django 5.1.4 on 2025-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_handbookcomponents_handbookconsumables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookcomponents',
            name='Название',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handbookconsumables',
            name='Название',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handbookequipments',
            name='Название',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
