# Generated by Django 5.1.4 on 2025-03-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_handbookequipments_модель_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Комплектующие'},
        ),
        migrations.AlterModelOptions(
            name='consumables',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Расходные материалы'},
        ),
        migrations.AlterModelOptions(
            name='equipments',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='exportfile',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Экспортные файлы'},
        ),
        migrations.AlterModelOptions(
            name='handbookcompany',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Справочники Компании'},
        ),
        migrations.AlterModelOptions(
            name='handbookcomponents',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Справочники Комплектующие'},
        ),
        migrations.AlterModelOptions(
            name='handbookconsumables',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Справочники Расходные материалы'},
        ),
        migrations.AlterModelOptions(
            name='handbookequipments',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Справочники Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='handbookprograms',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Справочники Программы'},
        ),
        migrations.AlterModelOptions(
            name='movements',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Перемещения'},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='repairs',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Ремонты'},
        ),
        migrations.AddField(
            model_name='handbookcomponents',
            name='Производитель',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
