# Generated by Django 5.1.4 on 2025-03-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_handbookcomponents_название_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookconsumables',
            name='сотрудник',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
