# Generated by Django 5.1.4 on 2025-03-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_handbookconsumables_сотрудник'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbookconsumables',
            name='сотрудник',
        ),
        migrations.AlterField(
            model_name='handbookconsumables',
            name='Сотрудник',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
