# Generated by Django 5.1.4 on 2025-03-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_components_options_alter_consumables_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookprograms',
            name='Производитель',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
