# Generated by Django 5.1.4 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_handbookprograms_производитель'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookconsumables',
            name='Производитель',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
