# Generated by Django 5.1.4 on 2025-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_handbookconsumables_сотрудник_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookequipments',
            name='Сотрудник',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
