# Generated by Django 5.1.4 on 2025-03-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_handbookequipments_сотрудник'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookprograms',
            name='Сотрудник',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
