# Generated by Django 5.1.4 on 2025-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_handbookconsumables_производитель'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='Дата_последней_заправки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='Дата_последней_проверки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='Дата_последней_проверки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customassetdetails',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customassetdetails',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customassetdetails',
            name='Дата_последней_проверки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Дата_последней_проверки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookcomponents',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookconsumables',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookequipments',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookprograms',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='Дата_Отправки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='Дата_Получения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='Дата_Инвертаризации',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='Дата_последней_проверки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='Дата_Возврата',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='Дата_Отправки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='Дата_Поломки',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='Ремонт_Дата_Изменения',
            field=models.DateField(blank=True, null=True),
        ),
    ]
